site_name: GAL - Gateway Abstraction Layer
site_description: Provider-agnostischer Konfigurations-Layer für API Gateways (Nginx, Envoy, Kong, APISIX, Traefik, HAProxy)
site_author: Dietmar Burkard
site_url: https://pt9912.github.io/x-gal/

repo_url: https://github.com/pt9912/x-gal
repo_name: pt9912/x-gal

exclude_docs: |
  README.md

theme:
  name: material
  language: de
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Zu Dunkelmodus wechseln
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Zu Hellmodus wechseln
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github

nav:
  - Start: index.md
  - Guides:
    - Schnellstart: guides/QUICKSTART.md
    - Konfigurationsbeispiele: guides/EXAMPLES.md
    - Best Practices: guides/BEST_PRACTICES.md
    - Provider Übersicht: guides/PROVIDERS.md
    - Nginx:
      - Übersicht: guides/NGINX.md
      - Features: guides/NGINX_FEATURES.md
      - Deployment & Migration: guides/NGINX_DEPLOYMENT.md
    - Envoy:
      - Übersicht: guides/ENVOY.md
      - Features: guides/ENVOY_FEATURES.md
      - Migration & Best Practices: guides/ENVOY_DEPLOYMENT.md
    - Kong:
      - Übersicht: guides/KONG.md
      - Features: guides/KONG_FEATURES.md
      - Migration & Best Practices: guides/KONG_DEPLOYMENT.md
    - APISIX:
      - Übersicht: guides/APISIX.md
      - Features: guides/APISIX_FEATURES.md
      - Best Practices & Troubleshooting: guides/APISIX_DEPLOYMENT.md
    - Traefik:
      - Übersicht: guides/TRAEFIK.md
      - Features: guides/TRAEFIK_FEATURES.md
      - Best Practices & Troubleshooting: guides/TRAEFIK_DEPLOYMENT.md
    - HAProxy:
      - Übersicht: guides/HAPROXY.md
      - Features: guides/HAPROXY_FEATURES.md
      - Best Practices & Troubleshooting: guides/HAPROXY_DEPLOYMENT.md
    - Azure API Management:
      - Übersicht: guides/AZURE_APIM.md
      - Features: guides/AZURE_APIM_FEATURES.md
      - Deployment & Migration: guides/AZURE_APIM_DEPLOYMENT.md
    - AWS API Gateway:
      - Übersicht: guides/AWS_APIGATEWAY.md
      - Features: guides/AWS_APIGATEWAY_FEATURES.md
      - Deployment & Migration: guides/AWS_APIGATEWAY_DEPLOYMENT.md
    - GCP API Gateway:
      - Übersicht: guides/GCP_APIGATEWAY.md
      - Features: guides/GCP_APIGATEWAY_FEATURES.md
      - Deployment & Migration: guides/GCP_APIGATEWAY_DEPLOYMENT.md
    - Transformationen: guides/TRANSFORMATIONS.md
    - Entwicklung: guides/DEVELOPMENT.md
  - Features:
    - Traffic Splitting: guides/TRAFFIC_SPLITTING.md
    - Request Mirroring: guides/REQUEST_MIRRORING.md
    - Authentication: guides/AUTHENTICATION.md
    - CORS: guides/CORS.md
    - Rate Limiting: guides/RATE_LIMITING.md
    - Circuit Breaker: guides/CIRCUIT_BREAKER.md
    - Health Checks: guides/HEALTH_CHECKS.md
    - Headers: guides/HEADERS.md
    - Logging & Observability: guides/LOGGING_OBSERVABILITY.md
    - Body Transformation: guides/BODY_TRANSFORMATION.md
    - gRPC Transformations: guides/GRPC_TRANSFORMATIONS.md
    - WebSocket: guides/WEBSOCKET.md
    - Timeout & Retry: guides/TIMEOUT_RETRY.md
  - Config Import & Migration:
    - Übersicht: import/migration.md
    - Envoy Import: import/envoy.md
    - Kong Import: import/kong.md
    - APISIX Import: import/apisix.md
    - Traefik Import: import/traefik.md
    - Nginx Import: import/nginx.md
    - HAProxy Import: import/haproxy.md
    - AWS API Gateway Import: import/aws-apigateway.md
    - Azure APIM Import: import/azure-apim.md
    - GCP API Gateway Import: import/gcp-apigateway.md
    - Compatibility: import/compatibility.md
  - API-Referenz:
    - CLI: api/CLI_REFERENCE.md
    - Konfiguration: api/CONFIGURATION.md
  - Architektur: architecture/ARCHITECTURE.md

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search:
      lang: de
  - tags

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pt9912/x-gal
  version:
    provider: mike

copyright: Copyright &copy; 2024-2025 Dietmar Burkard - MIT License
